### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by oOoBsBoOo** [DeekyJay/SoundwaveInteractive-releases#5] opened 2017-05-27 23:11 UTC
i launch my mixer pro webpage and execute my soundwave app but it wont launch on the mixer website under my channel ?

**Comment by MrFarquar** [comment] 2017-05-28 10:50
I'm having launch issues, SI is installed,and my Mixer account has authenticated it but I am still being asked to log in and wait when launching. Any help would be great, Thanks MrFarquar.

**Comment by fabudad** [comment] 2017-05-31 03:30
Im having similar problems. What my SI has issue with stay connected. 1 sec is another sec is not and the page stay refreshing for ever. Not sure if the answer to the issue is SI 2.0 or a update to the current on after the Mixer take over. Any comment will help. Thanks Ralph.

**Comment by DeekyJay** [comment] 2017-06-02 15:26
The connection issue has been resolved with the latest version! :)

**Closed as completed by DeekyJay** 2017-06-02 15:26 UTC
